name: hello                               # workflow name

on: [push]                                # trigger | webhooks, scheduled

jobs:                                     # block of actions/jobs
  build:
    runs-on: ubuntu-latest                # OS to run the actions in
    steps:                                # each step has access to the file-system but runs in it's own process
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
